// Copyright © 2026 Christopher Snow

// The words of Chapter 1, "The invisible data system": an essay in five ideas, on why a system's
// state is not its story. The prose is the teacher; the lab appears once, where doing teaches
// better than reading (CLAUDE.md: the experience is a means, not the law). Every number is
// pinned by invisible-system.facts.test.ts, read off the lab.

export const PROSE = {
  question:
    "A data system - a file share, a warehouse, a reporting stack - carries two very different kinds of information.\n\n- **State**: what exists right now. The files, the tables, the dashboards, the rows and columns, the timestamps.\n- **History**: how it came to be. What changed, when, why, who was responsible, and what depends on what.\n\nState is easy to read: open the folder, query the catalog, load the dashboard. History is not written anywhere in the state itself. **Metadata** is the discipline of recording that history, at the time it happens, so that the questions state cannot answer still have answers.\n\nThe example this chapter returns to is one shop on its first Monday: the shop below sells bicycle parts, its first week of orders has just finished, and the head of the shop has sent its new data engineer one line - *Thursday's revenue looks wrong*.",
  labDetails:
    "The shop, its people and its data are invented. The lab holds the shop's first week: real rows in files and tables, dashboard values and SQL programs. Its query engine runs the shop's programs and your queries. Nothing about the shop is kept between page loads: each load builds its data and runs its first week night by night, in memory. Every reader sees the same rows, results and times on any day. Dates and times come from the shop's first week, not from today or your computer's clock. Your browser keeps your work by chapter: predictions, choices and challenge answers. Nothing you do leaves your browser.",
  platformLead:
    "The shop's platform: three systems, and data moves through them in this order every night. The button at the foot of the window reopens it once you have scrolled past.",
  platformAfter: "An asset is one thing the platform holds: here, a file, a table or a dashboard.",
  weekLead:
    "The shop's first week ran from Monday 7 to Sunday 13 September. Each night, in the early hours of the next day, the three files are written again, then programs write the tables and refresh the dashboard. The last night ends early on Monday 14 September, before you start work.",
  exploreLead:
    "Four assets carry this chapter's example: the raw orders, the cleaned orders, the daily totals, and the reporting view built on them. Open each to see what it holds. Nothing is asked here.",
  dashboardLead: "",
  dashboardAfter:
    "Thursday shows 51.50, far below the days either side of it. The head of the shop is right: Thursday shows 51.50 against 153.75 the day before and 204.24 the day after. This chapter is about what can and cannot be established about that from the platform itself.",
  motivation:
    "Ask the kind of question anybody can ask a data engineer about a platform they did not build:\n\n- Who created this table, and for what purpose?\n- Did it always have these columns, or were some added last quarter - and by whom, for what?\n- Why does this dashboard exist? Whose decision does it serve?\n- A column was renamed last month. What was it called before, and what broke when it changed?\n\nThe system answers none of these from its state.",
  prediction:
    "Thursday is the chapter's case study: 205.50 of raw orders became a reported total of 51.50, and the state holds no record of how.",
  investigation:
    "A system's files, tables and dashboards show what exists now. Nothing in them says how it came to be, what changed, or why.\n\nLook at the week's assets. `daily_sales` keeps one row per day: the day and its revenue. You can see its columns, its rows, its owner, its last-modified time. Now ask the questions above, of it: who created it, for what purpose, what its columns were before, what breaks if one changes. The systems answer none of them.\n\nThe moment something is overwritten, renamed, rebuilt or deleted, the previous world is gone - unless someone recorded it. Thursday's own numbers show this twice over. The raw orders in `orders.parquet` add up to 205.50 for Thursday, while the dashboard and the table behind it both report 51.50. The state holds both numbers, and nothing between them: no record of what the nightly programs actually did, no record of which orders each step counts, no record of who chose the rules. A second difference is quieter and more telling: on three days (Monday, Friday, Sunday) the raw and reported totals match, and on four (Tuesday, Wednesday, Thursday, Saturday) they differ - a systematic pattern in the state, whose cause the state does not carry.\n\nEvery system answers *what is there?* fluently, and *how did it get here?* not at all.",
  construction:
    "Systems do record things - timestamps, owners, row counts, column names and types. But look closely at what a system actually stores, and you find a pattern: **each field is one the system needs for its own work.**\n\n- A last-modified time exists so the system can cache, sync or clean up. Object storage keeps each file's location and size to serve it; a Parquet file carries its own column names and types to be read.\n- An owner field exists so the system knows which account has rights. The warehouse records `etl_service` for all three of its tables - the account its four programs log in as - and nothing more.\n- A column-and-type definition exists so the system can validate writes and plan queries. The reporting tool keeps the dashboard's values because it needs them to draw its chart.\n\nThese fields answer questions about state: which assets exist, their columns and rows, when each was last written, which account owns a table. That is what they are for.\n\nThis is why you cannot get history by reading a system harder. The fields are not history fields with gaps - they are state fields, kept for the system's own work. None of them was ever meant to say why a change happened, what changed, who decided it, or what came before. Expecting a system's own fields to serve as a history of the system is like expecting a shop's inventory count to explain last year's business strategy.\n\nThe proof is in what the shop's owner field cannot do. \"Who should I ask about `daily_sales`?\" asks for a person or a team. The record names `etl_service` - an account four programs share. It answers *which account controls the table*, which is a different question wearing the same word.",
  failureExperiment:
    "When state cannot answer a question, the natural move is to reconstruct: infer the past from the traces that remain. This can work - but it produces *evidence*, never *proof*. Consider the most common reconstruction: *a query that reproduces the table, so that is how it was made.*\n\nThe shop makes this concrete. A query over `clean_orders` - keeping completed orders, adding up price times quantity per day - reproduces `daily_sales` exactly. It is a good reconstruction: it fits every row. And it fails in three ways, each of which the lab can show.\n\n**A copy fits equally.** Suppose an analyst copies `clean_orders` to a scratch bucket every night, as one of the three changes below can. Now two queries reproduce the table: the one over `clean_orders` and the same one over the copy. The data cannot say which the table was built from; both fit the evidence equally. No metadata identifies who created the copy or why. Evidence that fits many stories proves none of them.\n\n**An edit can leave nothing that fits.** Suppose the program that writes `daily_sales` is edited to keep orders that are not refunded. In the shop every order is completed or cancelled, so after the edit every order counts. Saturday's row now reads 215.49, not the 191.49 of the week as it first ran; Sunday's is unchanged. The table still has 7 rows and the same last-written time. And now no query in the builder's choices reproduces the table at all - the evidence that supported the explanation is simply gone, and nothing in the systems says why.\n\n**A failed night can leave a stale table looking current.** Suppose the program that writes `daily_sales` fails on the last night and writes nothing. The table now has 6 rows, with no row for Sunday, and was last altered on Sunday at 02:30 - a day before `clean_orders` and the dashboard. The dashboard refreshed on Monday at 03:00 as on every morning, and shows 6 values; its own record shows that Monday-morning refresh, so it looks up to date. The systems show that `daily_sales` is a day behind. They do not show that a write was due on Monday, or that one failed. Every trace the reconstruction relies on says normal; only a record of the failure would say otherwise.\n\nReconstruction reasons from traces to causes. The same traces fit multiple causes; edited traces fit no cause; and failed processes can leave traces indistinguishable from success.",
  explanation:
    "Even when a reconstruction is checkable, it can only be checked against what the data actually does. A reconstruction embeds rules - assumptions about how the system behaves - and those rules get validated only where the data exercises them.\n\nThe lab's own data shows this. Its cleaning step drops orders with a quantity of 0 or less - a rule the shop's program really has. But no order in this week's data has a quantity of 0 or less. The rule never fires, never rejects anything, and never leaves a distinguishing trace: a week with the rule and a week without it produce identical output. Two settings of the recovered rules pass the check, and the data cannot tell those two worlds apart.\n\n**A rule that never fires leaves no evidence it exists, and no evidence it doesn't.** A reconstruction validated only on traces inherits whatever behaviour the data happened to exercise, and is untested about the rest.",
  generalisation:
    "Put the four gaps together:\n\n- State does not contain history. The files, tables and dashboard show what exists now, and nothing of how it came to be.\n- The fields a system records are chosen for its own work, not for history. Timestamps, owners and column types exist for the system's work; they answer state questions only.\n- Inferring the past from traces yields evidence that fits multiple stories, or none, or looks normal after failures.\n- Even checkable reconstructions are unvalidated wherever the data never exercises the rule.\n\n**What happened, why, who was responsible, and what depends on what cannot be read from state - they need records made at the time.** After the fact is too late: the traces are already lossy, ambiguous and incomplete, and no amount of clever inference restores what was never captured.\n\nThree kinds of record are essential:\n\n| Question | Record made at the time | For the shop's `daily_sales` |\n|---|---|---|\n| **What is the asset?** | A description of the asset itself | What the table means, what it is for, who is responsible for it |\n| **What happened?** | A record of what happened | The failed night, the edited program, each with when, what changed, and whether the run succeeded |\n| **What was made from what?** | A record of what was made from what | The table is built from the cleaned, completed orders; the dashboard reads the table |\n\nThe three records answer questions that state-reading cannot. Real platforms do retain some history outside them - query logs, snapshots, audit trails - but those are records kept at the time, not reconstructions after the fact. The distinction that matters is not the container but the moment: evidence captured while it happened, or inference from what survived.\n\nAnd they share one requirement: **they must be captured as it happens.** A record of what was made from what, written after the fact, is itself a reconstruction, with all the ambiguity that brings. A failure record written the next morning is a memory, not a record. Metadata is a discipline of the present, kept for the future.",
  changeLead:
    "Reconstruction reasons from traces to causes. The three failures are what that means in practice.",
  c2Lead: "A reconstruction can be wrong where the data never exercises the rule.",
  reflection:
    "Back on the Monday morning: what would you have written down about `daily_sales` so that the next engineer need not reconstruct it? Who should have written it, and when - at the moment each program ran, or once, when the table was made?",
  modelVsReality:
    "Some real systems keep history that the lab's warehouse does not. An Apache Iceberg table keeps snapshots, each the state of the table at some time. A Delta Lake table keeps, for each write, the operation, the user and the time, for 30 days by default. The lab's systems keep only the current rows.\n\nIn some real databases, a table's owner is an account too. In PostgreSQL, for example, a new table's owner is normally the account that created it. At first, only the owner (or a superuser) can do anything with the table; other accounts can use it once they are given the right to. The right to alter or drop the table comes with being its owner. The lab's warehouse records the owning account and models no such rights.\n\nThe lab's sizes are estimates from the rows.\n\nThe lab works in UTC and has no time zones.\n\nA real platform has hundreds or thousands of assets. Searching for queries that rebuild one would cost far more.\n\nThe lab's search covers only the query builder's choices. \"None of the builder's choices rebuilds it\" means none of those choices; a query outside them might.",
} as const;
