// Copyright © 2026 Christopher Snow

// The words of Chapter 1, "The invisible data system": an essay on what a platform's state records
// and what it cannot say about how its assets came to be. Every number is pinned by
// invisible-system.facts.test.ts, read off the engine (packages/lab), which the page never names.

export const PROSE = {
  question:
    "You start work on Monday 14 September 2026 at 09:00, as the data engineer of an online shop that sells bicycle parts. The shop opened its online store a week ago, on Monday 7 September. Nobody who built its data platform is there to ask, and nothing about it is written down. Before you have sat down, the head of the shop sends you one line: Thursday's revenue looks wrong.\n\nThe platform has three systems: object storage, which holds files; a warehouse, which holds tables; and a reporting tool, which holds a dashboard. Every night, programs read the files, write the tables and refresh the dashboard. You can read everything the three systems hold. You cannot see the programs, when they are due to run, or any note anybody kept.",
  platformLead:
    "The three systems, in the order data moves through them each night. The button at the foot of the window reopens this figure once you have scrolled past it.",
  platformAfter: "An asset is one thing the platform holds: here, a file, a table or a dashboard.",
  weekLead:
    "The shop's first week ran from Monday 7 to Sunday 13 September. Each night, in the early hours of the next day, the three files are written again, then programs write the tables and refresh the dashboard. The last night ends early on Monday 14 September, before you start work.",
  exploreLead: "The four assets this chapter uses: open a card to see what the asset holds.",
  dashboardAfter: "Thursday shows 51.50, against 153.75 on Wednesday and 204.24 on Friday.",
  motivation:
    "Questions like the head of the shop's arrive every week on a platform you did not build:\n\n- Is Thursday's total wrong, and since when?\n- Can we delete `products.parquet`? Does anything still read it?\n- If the checkout renames a column in `orders.parquet`, what stops working?\n- Who should I ask about `daily_sales`?\n\nEach is answered by something that happened, or by a decision somebody made: a program that reads a file, a rule somebody chose, a person who took responsibility. None of them is answered by the rows a table holds today.",
  prediction:
    "Start with the arithmetic. `orders.parquet` holds every order the shop took, as the checkout sent it. Thursday's orders add up to 205.50. `daily_sales` holds one row per day, and its Thursday row says 51.50; the dashboard shows the same. Somewhere between the file and the table, 154.00 went missing.\n\nIt is not only Thursday. On Monday, Friday and Sunday the raw orders add up to the day's row in `daily_sales`. On Tuesday, Wednesday, Thursday and Saturday they do not. The platform holds both sets of numbers and nothing that connects them: no record of which orders `daily_sales` counts, which program decided that, or why.",
  investigation:
    "Take `daily_sales`. The warehouse records two columns, `day` and `revenue`, with their types; 7 rows and a size in bytes; a created time, 1 September, and a last-altered time, 02:30 on Monday 14 September; and an owner, `etl_service`. It records nothing else about the table.\n\nObject storage records as much about a file: its location, its size and when it was last modified. A Parquet file also carries its own column names and types, written inside the file. The reporting tool records the dashboard's title, who created it and when, when it last refreshed, and the values it shows.\n\nEverything here describes the asset as it is this morning. No field describes how it got that way: which program wrote it, what it read, what its rows were yesterday, or who decided its rules. The platform has a complete picture of its own state and no account of its history.",
  construction:
    "These fields exist because the systems need them. The warehouse keeps column names and types so that it can run a query; object storage keeps a file's location so that it can serve the file; the reporting tool keeps the values so that it can draw the chart. In the shop's platform, and in most real ones, a system records what its own work needs and nothing more. The questions you want answered are not its work.\n\nThe owner field shows how far that goes. \"Who should I ask about `daily_sales`?\" wants a person or a team. The warehouse answers `etl_service`, the account that all four of the shop's programs log in as. The field is called owner, but the question it answers is which account controls the table. The requirement that every table has an owner is met, and your question is not.",
  failureExperiment:
    "When the platform records no history, the usual move is to infer it from the data. For `daily_sales`, that means finding a query over another asset that gives the same rows. One does: read `clean_orders`, keep the completed orders, add up price times quantity per day. It reproduces `daily_sales` exactly, all seven rows. It also explains Thursday: three of Thursday's orders arrived with no customer id, `clean_orders` does not have them, and they are worth 154.00.\n\nThe query is evidence of how the table could have been made, not a record of how it was made, and three small changes to the shop show the difference.\n\nAn analyst copies `clean_orders` to a scratch bucket every night. Now the same query over the copy reproduces `daily_sales` too. None of the platform's records says which of the two the program reads. A query that fits is evidence for every source it fits.\n\nThe program that writes `daily_sales` is edited, from Saturday's row on, to keep every order that has not been refunded. The shop has no refunds, so from Saturday every order counts, cancelled ones included. Saturday's row becomes 215.49 instead of 191.49. The table still has 7 rows and the same last-altered time, and no simple query over the week's assets reproduces it any more. The evidence has gone, and the platform records nothing about the edit.\n\nOn the last night the program that writes `daily_sales` fails and writes nothing. The table has 6 rows, none for Sunday, and was last altered on Sunday at 02:30, a day earlier than `clean_orders` and the dashboard. The dashboard refreshed at 03:00 on Monday as usual and shows the 6 values it found. Everything the platform records looks like a normal morning with one row fewer. Only a record of the failure would say that a write was due and did not happen.",
  explanation:
    "A reconstruction can be checked against the data, but only where the data has something to check. `clean_orders` is made from `orders.parquet` by a few rules: keep one row of an order the export wrote twice, drop orders with no customer id, keep cancelled orders, and drop orders with a quantity of 0 or less. The last rule is in the program. No order in the week has a quantity of 0 or less, so the rule never removes a row, and a version of the program without it would have produced the same table. From the data, you cannot tell whether the rule exists. The data can confirm a rule only where some row would have triggered it.",
  generalisation:
    "The questions at the start need three kinds of record, none of which the platform keeps:\n\n- what an asset is: what `daily_sales` means, what it is for, and who is responsible for it;\n- what happened: each night's write of `daily_sales`, when it ran, what it read, and whether it succeeded;\n- what was made from what: `daily_sales` is built from the completed orders in `clean_orders`, and the dashboard reads `daily_sales`.\n\nInformation of this kind, about an asset or about the platform, is called metadata: what an asset is, where it came from, who is responsible for it, what its numbers mean, how it is made, and how it relates to other assets. Some of it the systems already keep for their own purposes: the names, types, counts and times you read above. The systems do not keep what an asset means, what happened to it or what it was made from; somebody has to record those, and the second and third have to be recorded when the thing happens. A note of what a program read, written the next morning from the data, is a reconstruction, with the limits shown above.\n\nReal platforms keep more history than the shop's: query logs, table snapshots, audit trails. Those are records made at the time too, kept by the system rather than by a person, and later chapters use them where they exist.",
  handover:
    "Suppose you had been the engineer who built the platform, handing it over on the Friday before you started. Write down, for `daily_sales` alone, what you would leave: what the table means and who to ask about it; what runs each night, reading what and writing what; and what the next engineer should do when a night fails. Then compare it with what the warehouse records: two column names, a row count, a size, two times and an account.",
  reflection:
    "The platform's state answers what exists. It does not answer what happened or why. Inferring the history from the data gave an explanation that fitted, and three ordinary changes made it ambiguous, made it wrong, or left a failed night looking like a normal one. The records that would have answered had to be made when the work was done.\n\nChapter 2 starts making them: a description of each asset, kept beside the data, with what the asset means and who is responsible for it. It then asks the four questions at the start again, to see which of them that record answers.",
  modelVsReality:
    "The shop, its people and its data are invented for the course.\n\nSome real systems keep history that the shop's warehouse does not. An Apache Iceberg table keeps snapshots, each the state of the table at some time. A Delta Lake table keeps, for each write, the operation, the user and the time, for 30 days by default. The shop's systems keep only the current rows.\n\nIn some real databases, a table's owner is an account too. In PostgreSQL, for example, a new table's owner is normally the account that created it. At first, only the owner (or a superuser) can do anything with the table; other accounts can use it once they are given the right to. The right to alter or drop the table comes with being its owner. The shop's warehouse records the owning account and no such rights.\n\nThe sizes shown are estimates from the rows. All times are UTC. A real platform has hundreds or thousands of assets; searching for queries that rebuild one would cost far more. \"No simple query reproduces it\" means none that keeps every row, completed orders or cancelled orders of one asset; a query with a condition on the date would.",
} as const;
